//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGCOMT.Web.App_GlobalResources {
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Usuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Usuario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Usuario", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellidos es requerido..
        /// </summary>
        internal static string ApellidoRequerido {
            get {
                return ResourceManager.GetString("ApellidoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellidos sólo permite un max. 50 caracteres..
        /// </summary>
        internal static string ApellidoStringLength {
            get {
                return ResourceManager.GetString("ApellidoStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        internal static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña y la contraseña de confirmación no coinciden..
        /// </summary>
        internal static string Coincidencia {
            get {
                return ResourceManager.GetString("Coincidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar la nueva contraseña.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Confirmar la Nueva Contraseña es obligatorio..
        /// </summary>
        internal static string ConfirmPasswordRequerido {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Débil.
        /// </summary>
        internal static string Debil {
            get {
                return ResourceManager.GetString("Debil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Correo no es una dirección de correo electrónico válida..
        /// </summary>
        internal static string EmailCorrecto {
            get {
                return ResourceManager.GetString("EmailCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo ya existe. Ingrese otro Correo..
        /// </summary>
        internal static string EmailDuplicado {
            get {
                return ResourceManager.GetString("EmailDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Correo Incorrecto.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Correo es requerido..
        /// </summary>
        internal static string EmailRequerido {
            get {
                return ResourceManager.GetString("EmailRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Correo sólo permite un max. 50 caracteres..
        /// </summary>
        internal static string EmailStringLength {
            get {
                return ResourceManager.GetString("EmailStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Contraseña actual es incorrecta..
        /// </summary>
        internal static string ErrorContraseña {
            get {
                return ResourceManager.GetString("ErrorContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuerte.
        /// </summary>
        internal static string Fuerte {
            get {
                return ResourceManager.GetString("Fuerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Idioma es requerido..
        /// </summary>
        internal static string IdiomalRequerido {
            get {
                return ResourceManager.GetString("IdiomalRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediana.
        /// </summary>
        internal static string Mediana {
            get {
                return ResourceManager.GetString("Mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea eliminar el usuario.
        /// </summary>
        internal static string MensajeConfirmEliminar {
            get {
                return ResourceManager.GetString("MensajeConfirmEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muy Débil.
        /// </summary>
        internal static string MuyDebil {
            get {
                return ResourceManager.GetString("MuyDebil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muy Fuerte.
        /// </summary>
        internal static string MuyFuerte {
            get {
                return ResourceManager.GetString("MuyFuerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nueva Contraseña es obligatorio..
        /// </summary>
        internal static string NewPasswordRequerido {
            get {
                return ResourceManager.GetString("NewPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombres es requerido..
        /// </summary>
        internal static string NombreRequerido {
            get {
                return ResourceManager.GetString("NombreRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string NombreRol {
            get {
                return ResourceManager.GetString("NombreRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        internal static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombres sólo permite un max. 30 caracteres..
        /// </summary>
        internal static string NombreStringLength {
            get {
                return ResourceManager.GetString("NombreStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Contraseña Actual es obligatorio..
        /// </summary>
        internal static string OldPasswordRequerido {
            get {
                return ResourceManager.GetString("OldPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel Usuario.
        /// </summary>
        internal static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Password debe ser mínimo de 6 caracteres..
        /// </summary>
        internal static string PasswordMinimo6 {
            get {
                return ResourceManager.GetString("PasswordMinimo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Password es requerido..
        /// </summary>
        internal static string PasswordRequerido {
            get {
                return ResourceManager.GetString("PasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Rol es obligatorio..
        /// </summary>
        internal static string RolRequerido {
            get {
                return ResourceManager.GetString("RolRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Teléfono sólo permite un max. 50 caracteres..
        /// </summary>
        internal static string TelefonoStringLength50 {
            get {
                return ResourceManager.GetString("TelefonoStringLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string TituloBusqueda {
            get {
                return ResourceManager.GetString("TituloBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string TituloPopupEditarUsuario {
            get {
                return ResourceManager.GetString("TituloPopupEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Usuario.
        /// </summary>
        internal static string TituloPopupNuevoUsuario {
            get {
                return ResourceManager.GetString("TituloPopupNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Username es requerido..
        /// </summary>
        internal static string UsernameRequerido {
            get {
                return ResourceManager.GetString("UsernameRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Username sólo permite un max. 100 caracteres..
        /// </summary>
        internal static string UsernameStringLength100 {
            get {
                return ResourceManager.GetString("UsernameStringLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username ya existe. Ingrese otro Username..
        /// </summary>
        internal static string UsuarioDuplicado {
            get {
                return ResourceManager.GetString("UsuarioDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Eliminar Usuario.
        /// </summary>
        internal static string UsuarioNoEliminado {
            get {
                return ResourceManager.GetString("UsuarioNoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o el correo ya existen..
        /// </summary>
        internal static string UsuarioOCorreoDuplicado {
            get {
                return ResourceManager.GetString("UsuarioOCorreoDuplicado", resourceCulture);
            }
        }
    }
}
